# Bisect Bot Secrets Configuration
# ================================
# 
# This is the ONLY secrets file you need to configure.
# Copy this file to secrets.yml and fill in your values.
#
# Usage:
#   cp secrets.example.yml secrets.yml
#   # Edit secrets.yml with your values
#   # Then run: terraform apply && ansible-playbook site.yml
#
# NEVER commit secrets.yml to version control!

# =============================================================================
# HETZNER CLOUD
# =============================================================================
# Get your API token from: https://console.hetzner.cloud
# Go to: Your Project → Security → API Tokens → Generate API Token
hcloud_token: "your-hetzner-api-token-here"

# Your SSH public key for server access
# Get it with: cat ~/.ssh/id_rsa.pub
ssh_public_key: "ssh-rsa AAAA... your-email@example.com"

# =============================================================================
# DOMAIN & SSL
# =============================================================================
# Your domain name (must be configured to point to Hetzner server after creation)
domain: "bisect.example.com"

# Email for Let's Encrypt SSL certificate notifications
admin_email: "admin@example.com"

# =============================================================================
# SUPABASE DATABASE
# =============================================================================
# Get these from: https://app.supabase.com
# Go to: Project Settings → Database → Connection string
#
# Use the POOLED connection (port 6543) for the application
database_url: "postgresql://postgres.[PROJECT-REF]:[PASSWORD]@aws-0-eu-central-1.pooler.supabase.com:6543/postgres"

# Use the DIRECT connection (port 5432) for migrations only
database_url_direct: "postgresql://postgres:[PASSWORD]@db.[PROJECT-REF].supabase.co:5432/postgres"

# =============================================================================
# GITHUB APP
# =============================================================================
# Create your GitHub App at: https://github.com/settings/apps/new
# See productionization.md for detailed setup instructions

# Found on the GitHub App settings page
github_app_id: "123456"

# The URL slug of your app (from the app URL)
github_app_slug: "your-bisect-bot"

# OAuth credentials (found in the GitHub App settings)
github_client_id: "Iv1.abc123def456"
github_client_secret: "your_client_secret_here"

# Webhook secret (you set this when creating the app)
# Generate with: openssl rand -hex 32
github_webhook_secret: "your_webhook_secret_here"

# GitHub App private key (the contents of the .pem file)
# Download from: GitHub App settings → Private keys → Generate a private key
# Paste the ENTIRE contents including BEGIN/END lines
github_private_key: |
  -----BEGIN RSA PRIVATE KEY-----
  MIIEpAIBAAKCAQEA...
  ...your private key here...
  -----END RSA PRIVATE KEY-----

# =============================================================================
# APPLICATION SECRETS
# =============================================================================
# Session encryption key (generate with: openssl rand -hex 32)
secret_key: "your-64-character-hex-session-key"

# Data encryption key for sensitive data at rest
# Generate with: python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"
encryption_key: "your-fernet-key-here"

# =============================================================================
# OPTIONAL SETTINGS
# =============================================================================
# Server configuration (defaults are good for most cases)
# server_type: "cx32"  # cx22 (dev), cx32 (recommended), cx42 (high traffic)
# location: "fsn1"     # fsn1 (Falkenstein), nbg1 (Nuremberg), hel1 (Helsinki)
# environment: "prod"  # prod, staging, dev

# Worker configuration
# worker_replicas: 2
# bisect_timeout_seconds: 1800

# Auto-scaling (enabled by default)
# autoscale_min_workers: 2
# autoscale_max_workers: 10

